name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        working-directory: backend
        run: poetry install

      - name: Run tests
        working-directory: backend
        run: poetry run pytest